apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-pod-rules
  labels:
    release: prometheus
spec:
  groups:
  - name: app-pods
    rules:
    - alert: PodDown
      expr: up == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheous target is down {{$labels.instance}}
        description: Application pod is down