apiVersion: v1
kind: Service
metadata:
  name: python-with-prometheus
  labels:
    app: python-with-prometheus
    job: web-service
spec:
  type: ClusterIP
  selector:
    app: python-with-prometheus
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: app